export default {
  dbName: ``,
  dbHost: "",
  dbUsername: "",
  dbPassword: "",
  saltWorkFactor: 10,
  accessTokenTtl: "15m",
  refreshTokenTtl: "1y",
  publicKey: ``,
  privateKey: ``,
  smtpHost: "",
  smtpPort: "",
  smtpUser: "",
  smtpPass: "",
};
